#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : drp_example.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu May 17 10:09:20 PDT 2018
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: drp_example.sh [-help]
# usage: drp_example.sh [-lib_map_path]
# usage: drp_example.sh [-noclean_files]
# usage: drp_example.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'drp_example.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 util_vector_logic_v2_0_1 jtag_axi generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_16 fifo_generator_v13_2_2 axi_data_fifo_v2_1_15 axi_crossbar_v2_1_17 gtwizard_ultrascale_v1_7_3 axi_protocol_converter_v2_1_16)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "drp_example.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_proc_sys_reset_0_0/sim/drp_example_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_util_vector_logic_0_0/sim/drp_example_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_clk_wiz_2_0/drp_example_clk_wiz_2_0_clk_wiz.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_clk_wiz_2_0/drp_example_clk_wiz_2_0.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_clk_wiz_3_0/drp_example_clk_wiz_3_0_clk_wiz.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_clk_wiz_3_0/drp_example_clk_wiz_3_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work jtag_axi $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/1cc2/hdl/jtag_axi_v1_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_jtag_axi_1_0/sim/drp_example_jtag_axi_1_0.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/47a6/rtl/drp_bridge.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_drp_bridge_1_0/sim/drp_example_drp_bridge_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/d293/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_xbar_2/sim/drp_example_xbar_2.v" \
    "$ref_dir/../../../bd/drp_example/sim/drp_example.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_system_ila_1_0/bd_0/sim/bd_aaba.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_system_ila_1_0/bd_0/ip/ip_0/sim/bd_aaba_ila_lib_0.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_system_ila_1_0/sim/drp_example_system_ila_1_0.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/sim/gty_quad_vio_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gty_quad_gtye4_channel_wrapper.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gtwizard_ultrascale_v1_7_gtye4_common.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gty_quad_gtye4_common_wrapper.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gty_quad_gtwizard_gtye4.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gty_quad_gtwizard_top.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad/sim/gty_quad.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_bit_sync.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_checking_raw.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_init.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_reset_sync.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_stimulus_raw.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_wrapper_functions.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_wrapper.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_prbs_any.v" \
    "$ref_dir/../../../bd/drp_example/ipshared/fd23/sim/gty_quad_example_top.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/sim/drp_example_gty_quad_example_top_0_0.v" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_drp_bridge_1_1/sim/drp_example_drp_bridge_1_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/1229/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/4903" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../bd/drp_example/ipshared/fd23/src" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2875/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/2c14/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl/verilog" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ip/drp_example_gty_quad_example_top_0_0/src/gty_quad_vio_0/hdl" +incdir+"$ref_dir/../../../../kcu116_jtag_prbs.srcs/sources_1/bd/drp_example/ipshared/fd23/src" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/drp_example/ip/drp_example_auto_pc_0/sim/drp_example_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.drp_example xil_defaultlib.glbl -o drp_example_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./drp_example_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./drp_example.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/chiwei/work/checkout/kcu116/kcu116_jtag_prbs/kcu116_jtag_prbs.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key drp_example_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc drp_example_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./drp_example.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: drp_example.sh [-help]\n\
Usage: drp_example.sh [-lib_map_path]\n\
Usage: drp_example.sh [-reset_run]\n\
Usage: drp_example.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
